baseURL = "http://keithmillar.github.io"
publishdir = "keithmillar.github.io"
languageCode = "en-us"
title = "Keith's Diary and Other Stuff"

[permalinks]
  blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Archive"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
   [[menu.main]]
    name = "Collections"
    pre = "database"
    url = "/collection/"
	weight = 4

[taxonomies]
  tag = "tags"

[params]
  dateFormat = "Jan 02, 2006"
#  homeText = "You just made a Hugo blog from scratch."

